package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseStore<M extends BaseStore<M>> extends JBoltBaseModel<M>{

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setSellerId(java.lang.Integer sellerId) {
		set("seller_id", sellerId);
		return (M)this;
	}
	
	public java.lang.Integer getSellerId() {
		return getInt("seller_id");
	}

	public M setLocation(java.lang.String location) {
		set("location", location);
		return (M)this;
	}
	
	public java.lang.String getLocation() {
		return getStr("location");
	}

	public M setSale(java.lang.Integer sale) {
		set("sale", sale);
		return (M)this;
	}
	
	public java.lang.Integer getSale() {
		return getInt("sale");
	}

	public M setScore(java.lang.Double score) {
		set("score", score);
		return (M)this;
	}
	
	public java.lang.Double getScore() {
		return getDouble("score");
	}

	public M setStorePhotoSrc(java.lang.String storePhotoSrc) {
		set("store_photo_src", storePhotoSrc);
		return (M)this;
	}
	
	public java.lang.String getStorePhotoSrc() {
		return getStr("store_photo_src");
	}

	public M setAllowDelivery(java.lang.Double allowDelivery) {
		set("allow_delivery", allowDelivery);
		return (M)this;
	}
	
	public java.lang.Double getAllowDelivery() {
		return getDouble("allow_delivery");
	}

	public M setDeliveryCost(java.lang.Double deliveryCost) {
		set("delivery_cost", deliveryCost);
		return (M)this;
	}
	
	public java.lang.Double getDeliveryCost() {
		return getDouble("delivery_cost");
	}

}
