package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseComment<M extends BaseComment<M>> extends JBoltBaseModel<M>{

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
		return (M)this;
	}
	
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setTime(java.util.Date time) {
		set("time", time);
		return (M)this;
	}
	
	public java.util.Date getTime() {
		return get("time");
	}

	public M setTotalScore(java.lang.Float totalScore) {
		set("total_score", totalScore);
		return (M)this;
	}
	
	public java.lang.Float getTotalScore() {
		return getFloat("total_score");
	}

	public M setPackageScore(java.lang.Float packageScore) {
		set("package_score", packageScore);
		return (M)this;
	}
	
	public java.lang.Float getPackageScore() {
		return getFloat("package_score");
	}

	public M setTasteScore(java.lang.Float tasteScore) {
		set("taste_score", tasteScore);
		return (M)this;
	}
	
	public java.lang.Float getTasteScore() {
		return getFloat("taste_score");
	}

}
