package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCommentPhotos<M extends BaseCommentPhotos<M>> extends JBoltBaseModel<M>{

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCommentId(java.lang.Integer commentId) {
		set("comment_id", commentId);
		return (M)this;
	}
	
	public java.lang.Integer getCommentId() {
		return getInt("comment_id");
	}

	public M setPhotoSrc(java.lang.String photoSrc) {
		set("photo_src", photoSrc);
		return (M)this;
	}
	
	public java.lang.String getPhotoSrc() {
		return getStr("photo_src");
	}

}
