package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseStore<M extends BaseStore<M>> extends JBoltBaseModel<M>{

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setSellerId(java.lang.Integer sellerId) {
		set("seller_id", sellerId);
		return (M)this;
	}
	
	public java.lang.Integer getSellerId() {
		return getInt("seller_id");
	}

	public M setLocation(java.lang.String location) {
		set("location", location);
		return (M)this;
	}
	
	public java.lang.String getLocation() {
		return getStr("location");
	}

	public M setScore(java.lang.Double score) {
		set("score", score);
		return (M)this;
	}
	
	public java.lang.Double getScore() {
		return getDouble("score");
	}

}
