package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseCommentPhotos;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class CommentPhotos extends BaseCommentPhotos<CommentPhotos> {
	//建议将dao放在Service中只用作查询 
	public static final CommentPhotos dao = new CommentPhotos().dao();
	//在Service中声明 可直接复制过去使用
	//private CommentPhotos dao = new CommentPhotos().dao(); 
}
