package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseOrderId;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class OrderId extends BaseOrderId<OrderId> {
	//建议将dao放在Service中只用作查询 
	public static final OrderId dao = new OrderId().dao();
	//在Service中声明 可直接复制过去使用
	//private OrderId dao = new OrderId().dao();  
}
