package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseOrder;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class Order extends BaseOrder<Order> {
	//建议将dao放在Service中只用作查询 
	public static final Order dao = new Order().dao();
	//在Service中声明 可直接复制过去使用
	//private Order dao = new Order().dao();  
}
