package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseOrders;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class Orders extends BaseOrders<Orders> {
	//建议将dao放在Service中只用作查询 
	public static final Orders dao = new Orders().dao();
	//在Service中声明 可直接复制过去使用
	//private Orders dao = new Orders().dao();  
}
