package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseProduct;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class Product extends BaseProduct<Product> {
	//建议将dao放在Service中只用作查询 
	public static final Product dao = new Product().dao();
	//在Service中声明 可直接复制过去使用
	//private Product dao = new Product().dao();  
}
