package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseProductType;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class ProductType extends BaseProductType<ProductType> {
	//建议将dao放在Service中只用作查询 
	public static final ProductType dao = new ProductType().dao();
	//在Service中声明 可直接复制过去使用
	//private ProductType dao = new ProductType().dao();  
}
