package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseShoppingAddress;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class ShoppingAddress extends BaseShoppingAddress<ShoppingAddress> {
	//建议将dao放在Service中只用作查询 
	public static final ShoppingAddress dao = new ShoppingAddress().dao();
	//在Service中声明 可直接复制过去使用
	//private ShoppingAddress dao = new ShoppingAddress().dao();  
}
