package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseShoppingCart;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class ShoppingCart extends BaseShoppingCart<ShoppingCart> {
	//建议将dao放在Service中只用作查询 
	public static final ShoppingCart dao = new ShoppingCart().dao();
	//在Service中声明 可直接复制过去使用
	//private ShoppingCart dao = new ShoppingCart().dao();  
}
