package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseStore;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class Store extends BaseStore<Store> {
	//建议将dao放在Service中只用作查询 
	public static final Store dao = new Store().dao();
	//在Service中声明 可直接复制过去使用
	//private Store dao = new Store().dao();  
}
