package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseStorePosition;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class StorePosition extends BaseStorePosition<StorePosition> {
	//建议将dao放在Service中只用作查询 
	public static final StorePosition dao = new StorePosition().dao();
	//在Service中声明 可直接复制过去使用
	//private StorePosition dao = new StorePosition().dao();  
}
